version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /opt/database/task-manager-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    container_name: zipkin

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq